spring:
  datasource:
    testOnBorrow: true
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa:
    properties:
      hibernate.cache.use_second_level_cache: true
      hibernate.cache.use_query_cache: false
      hibernate.cache.region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    initialize: false
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cardwizard?useUnicode=true&characterEncoding=utf8
    username: cardwizard
    password: cardwizard